//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cc.isr.VI.WinControls.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("cc.isr.VI.WinControls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clear_22x22 {
            get {
                object obj = ResourceManager.GetObject("Clear_22x22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Connected_22x22 {
            get {
                object obj = ResourceManager.GetObject("Connected_22x22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Disconnected_22x22 {
            get {
                object obj = ResourceManager.GetObject("Disconnected_22x22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EventHandleGreen16 {
            get {
                object obj = ResourceManager.GetObject("EventHandleGreen16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Find_22x22 {
            get {
                object obj = ResourceManager.GetObject("Find_22x22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lightning_16 {
            get {
                object obj = ResourceManager.GetObject("lightning_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables reading of polled messages.
        ///Checking the Show Polled Reading from the Session panel displays the messages on the Session panel..
        /// </summary>
        internal static string PollAutoReadHint {
            get {
                return ResourceManager.GetString("PollAutoReadHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables reading of service request messages.
        ///Checking the Show Service Request Reading from the Session panel displays the messages on the Session panel..
        /// </summary>
        internal static string ServiceRequestAutoReadHint {
            get {
                return ResourceManager.GetString("ServiceRequestAutoReadHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When checked, the program activates the device status subsystem.
        ///Other subsystems, such as Multimeter, Source, Trigger or Trace, remain inactive..
        /// </summary>
        internal static string StatusSubsystemOnlyHint {
            get {
                return ResourceManager.GetString("StatusSubsystemOnlyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The terminal state, F (front) or R (rear), appears at the left side of the display panel.
        ///Terminal state is read when supported on instruments such as the Keithley 2002, 7510, 6510 or 2450..
        /// </summary>
        internal static string TerminalsHint {
            get {
                return ResourceManager.GetString("TerminalsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled, VISA notifies the program of instrument events.
        ///The event handler Bitmask defines which events are notified.
        ///The Device service request handler handles these events.
        ///A lightning bolt image appears at the bottom of the display panel when VISA is set to notify of instrument events.
        ///A lightning bolt handle appears at the bottom of the display panel when an event handler is assigned to handle the VISA event..
        /// </summary>
        internal static string ToggleVisaEventHandlerHint {
            get {
                return ResourceManager.GetString("ToggleVisaEventHandlerHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the amount of information logged or displayed. 
        ///Setting the level to Verbose permits all messages.  
        ///Setting it to Warning permits only Errors and Warnings..
        /// </summary>
        internal static string TraceHint {
            get {
                return ResourceManager.GetString("TraceHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user_offline_2 {
            get {
                object obj = ResourceManager.GetObject("user_offline_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user_online_2 {
            get {
                object obj = ResourceManager.GetObject("user_online_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
